version: '3'
services:
    web:
        build: .
        ports:
            - "8080:8080"
    influxdb:
        image: influxdb:1.4.3
        volumes:
            - influxdata:/var/lib/influxdb
        ports:
            - "8086:8086"
    chronograf:
        image: chronograf:1.3.10.0-alpine
        environment:
            INFLUXDB_URL: http://influxdb:8086
        volumes:
            - chronografdata:/var/lib/chronograf
        ports:
            - "8888:8888"
        links:
            - influxdb
       
volumes:
    influxdata:
    chronografdata: