-- INSERT INTO car(id, name, time, oilLevel) VALUES (1, 'car1', 1, 1);
-- INSERT INTO car(id, name, time, oilLevel) VALUES (2, 'car2',2, 2);
-- INSERT INTO car(id, name, time, oilLevel) VALUES (3, 'car3',3, 3);
-- INSERT INTO car(id, name, time, oilLevel) VALUES (4, 'car4',4, 4);